{% set name = "pykx" %}
{% set version = "2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/KxSystems/pykx
  git_rev: release/{{ version }}
  patches:
    - 0001-Addition-of-missing-file.patch

build:
  script:
    - rm -rv $SRC_DIR/src/pykx/lib/[l,w]64*   # [osx]
    - rm -rv $SRC_DIR/src/pykx/lib/[m,w]64*   # [linux]
    - del /s %SRC_DIR%/src/pykx/lib/l64 %SRC_DIR%/src/pykx/lib/l64arm %SRC_DIR%/src/pykx/lib/m64 %SRC_DIR%/src/pykx/lib/m64arm  # [win]
    - {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - cython 3.0.0
    - numpy 1.22  # [py!=37]
    - numpy 1.20  # [py==37]
    - setuptools
    - setuptools-scm 7.1.0
    - tomli 2.0.1
    - wheel
    - pip
  run:
    - python
    - pandas >=1.2
    - pytz >=2022.1
    - toml >=0.10.2,<0.11.0
    - {{ pin_compatible('numpy') }}

# skip these tests because they require a valid license from kx
#{% set tests_to_skip = "test_licensed_success_file or test_licensed_success_b64" %}

test:
  source_files:
    - tests
  commands:
    #- export QARGS="--unlicensed" # [not win]
    - set QARGS="--unlicensed"    # [win]
    - pip check
    - python -c "import pykx"
    - mkdir q                     # [not win]
    - mkdir q                     # [win]
    - export QHOME=q              # [not win]
    - set QHOME=q                 # [win]
    - export QLIC=q               # [not win]
    - set QLIC=q                  # [win]
    - python -c "import base64, os; t = '<insert-license-here>'; t = t.encode('ascii'); decoded = base64.decodebytes(t); bf = open(os.path.join('q','kc.lic'), 'wb'); bf.write(decoded); bf.close()"
    #- pytest -v -m "not licensed" -k "not ({{ tests_to_skip }})" tests
    - pytest -v tests
  requires:
    - pip
    - plotly
    - pytest
    - pytest-asyncio
    - pytest-benchmark
    - pytest-monitor  # [not osx]
    - pytest-xdist
    - psutil
    - pytest-timeout

about:
  home: https://code.kx.com/pykx
  license: LGPL-3.0 AND Apache-2.0
  license_file:
    - LICENSE.txt
    - src/pykx/license.py
  license_family: Other
  summary: An interface between Python and q.
  description: |
    PyKX is a Python first interface to the worlds fastest time-series database kdb+ and it's underlying vector
    programming language q. PyKX takes a Python first approach to integrating q/kdb+ with Python following 10+ years of
    integrations between these two languages. Fundamentally it provides users with the ability to efficiently query and
    analyze huge amounts of in-memory and on-disk time-series data.
  doc_url: https://code.kx.com/pykx
  dev_url: https://github.com/KxSystems/pykx

extra:
  recipe-maintainers:
    - boldorider4
