{% set name = "pykx" %}
{% set version = "None" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/KxSystems/pykx
  git_rev: release/2.1

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python >=3.7
    - cython >=3.0.0,<3.1.dev0
    - numpy >=1.22,<2.dev0,<1.23  # [py!=37]
    - setuptools ==60.9.3
    - setuptools-scm >=6.0.1,<6.1.dev0
    - tomli >=2.0.1
    - wheel >=0.36.2
    - pip
  run:
    - python >=3.7
    - pandas >=1.2
    - pytz >=2022.1
    - toml >=0.10.2,<0.11.dev0
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - pykx
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://code.kx.com/pykx
  license: LGPL-3.0 AND Apache-2.0
  license_file:
    - LICENSE.txt
    - src/pykx/license.py
  license_family: Other
  summary: An interface between Python and q.
  description: |
    PyKX is a Python first interface to the worlds fastest time-series database kdb+ and it's underlying vector
    programming language q. PyKX takes a Python first approach to integrating q/kdb+ with Python following 10+ years of
    integrations between these two languages. Fundamentally it provides users with the ability to efficiently query and
    analyze huge amounts of in-memory and on-disk time-series data.
  doc_url: https://code.kx.com/pykx
  dev_url: https://github.com/KxSystems/pykx

extra:
  recipe-maintainers:
    - boldorider4
